


 var array_1 = ["id",	"orgname",	"orgfurigana",	"management",	"kind",	"segment",	"segment2",	"supportclass",	"loginid",	"password",	"password2",	"password3",	"usersnum",	"zip",	"pref", "address1" , "address2",	"personname",	"personfurigana",	"tel",	"fax",	"mail",	"orgcheckestate",	"repostingclass",	"lastlogintime",	"lastsupportdate",	"nextsupportdate",	"contractdate",	"agreementflg",	"created",	"modified",	"org_mst_data_id",	"classlist",	"bankaccount",	"userlimit",	"revise",	"watermarkflg",	"watermarkdepth",	"orgdeliveryprice",	"bulkpostageclass",	"orgpermit",	"ordercsvflg",	"overlapflg",	"price",	"unitclass",	"unitdiscountday",	"postageclass",	"freepostage",	"commissionclass",	"deliverymethod",	"dateprint",	"sort",;
 var array_2 = ["id",	"loginid",	"password",	"password2",	"password3",	"kind",	"segment",	"segment2",	"supportclass",	"belongclass",	"belongid",	"orgname",	"orgfurigana",	"management",	"usersnum",	"zip",	"pref",	"address1",	"address2",	"personname",	"personfurigana",	"tel",	"fax",	"mail",	"availabletime",	"classlist",	"bankaccount",	"bankaccount2",	"price",	"price2",	"unitclass",	"unitdiscountday",	"postageclass",	"freepostage",	"commissionclass",	"deliverymethod",	"dateprint",	"sort",	"dlpermission",	"numbertype",	"userlimit",	"revise",	"watermarkflg",	"watermarkdepth",	"orgdeliveryprice",	"bulkpostageclass",	"orgpermit",	"ordercsvflg",	"overlapflg",	"orgcheckestate",	"importantinfo",	"memo",	"repostingclass",	"repostingclassother",	"albumclass",	"albumclassother",	"contractdate",	"lastsupportdate",	"nextsupportdate",	"contractorgmoddate",	"lastlogintime",	"taxincflg",	"created",	"modified",	"agreementflg",	"bankaccount3",	"id",	"loginid",	"password",	"password2",	"password3",	"kind"];
 var array_3 = ["id",	"loginid",	"password_1",	"password_2",	"parent_org_id",	"name",	"delivery_method",	"name_kana",	"secret",	"email",	"email_confirm",	"kind",	"is_display_name",	"pattern_captions",	"segment",	"is_date_stamp",	"number_type",	"person_name",	"person_name_kana",	"phone",	"tax",	"postal_code",	"prefecture",	"city",	"address1",	"address2",	"edited_profile_at",	"edited_sale_price_at",	"use_storage",	"alert_sale_price_a4",	"created_at",	"updated_at",	"deleted_at"]
 let arr = [array_1, array_2, array_3];
 // Get common items of both array_1, array_2
 let myFunction = function (x, y) {
    content.innerHTML = arr.reduce((x, y) =>
       x.filter((z) => y.includes(z))
 );