var date = new Date()
// 2. Từ bài 1, lấy ra năm hiện tại (4 chữ số)
var year = date.getFullYear()
console.log(year)
// 3. Từ bài 1, lấy ra tháng hiện tại (2 chữ số)
var month = date.getMonth()+1
console.log(month)
// 4. Từ bài 1, lấy ra ngày hiện tại (2 chữ số)
var dt = date.getDate()
console.log(dt)